import type { ExamQuestion } from '@life-sim/core';

export const examBank: ExamQuestion[] = [
  {
    id: 'q_chinese_idiom',
    track: 'both',
    subject: '语文',
    text: '下列句子中,加点成语使用恰当的一项是:',
    options: [
      '他的演讲抛砖引玉,赢得了满堂喝彩',
      '这部小说情节跌宕起伏,读来令人爱不释手',
      '比赛结束后,双方队员济济一堂地退场了',
      '他做事一向首当其冲,从不推脱责任',
    ],
    answerIndex: 1,
    difficulty: 2,
  },
  {
    id: 'q_math_set',
    track: 'both',
    subject: '数学',
    text: '已知集合 A = {1, 2, 3, 4},B = {x | x² ≤ 4},则 A ∩ B =',
    options: ['{1}', '{1, 2}', '{1, 2, 3}', '{2}'],
    answerIndex: 1,
    difficulty: 2,
  },
  {
    id: 'q_english_cloze',
    track: 'both',
    subject: '英语',
    text: 'The movie was so boring that half of the audience left ___ it ended.',
    options: ['after', 'since', 'before', 'until'],
    answerIndex: 2,
    difficulty: 1,
  },
  {
    id: 'q_math_func',
    track: 'both',
    subject: '数学',
    text: '函数 f(x) = 2x + 1,若 f(a) = 7,则 a =',
    options: ['2', '3', '4', '5'],
    answerIndex: 1,
    difficulty: 1,
  },
  {
    id: 'q_physics_fall',
    track: '理',
    subject: '理综·物理',
    text: '一物体从静止开始自由下落,2 秒末的速度约为(g 取 10 m/s²):',
    options: ['10 m/s', '20 m/s', '40 m/s', '5 m/s'],
    answerIndex: 1,
    difficulty: 1,
  },
  {
    id: 'q_chem_gas',
    track: '理',
    subject: '理综·化学',
    text: '下列气体中,能使湿润的红色石蕊试纸变蓝的是:',
    options: ['二氧化碳', '氯气', '氨气', '二氧化硫'],
    answerIndex: 2,
    difficulty: 2,
  },
  {
    id: 'q_history_jiawu',
    track: '文',
    subject: '文综·历史',
    text: '甲午中日战争后签订的条约是:',
    options: ['《南京条约》', '《马关条约》', '《辛丑条约》', '《北京条约》'],
    answerIndex: 1,
    difficulty: 1,
  },
  {
    id: 'q_geo_timezone',
    track: '文',
    subject: '文综·地理',
    text: '当北京时间为 12:00 时,伦敦(中时区)的区时约为:',
    options: ['4:00', '20:00', '12:00', '8:00'],
    answerIndex: 0,
    difficulty: 2,
  },
  {
    id: 'q_chinese_sentence',
    track: 'both',
    subject: '语文',
    text: '下列句子中没有语病的一项是:',
    options: [
      '通过这次活动,使我们认识到阅读的重要性',
      '能否坚持锻炼,是身体健康的重要保证',
      '学校开展了丰富多彩的社团活动',
      '他大约用了整整两个小时左右完成作业',
    ],
    answerIndex: 2,
    difficulty: 2,
  },
  {
    id: 'q_chinese_poem',
    track: 'both',
    subject: '语文',
    text: '"落霞与孤鹜齐飞,秋水共长天一色"出自:',
    options: ['《岳阳楼记》', '《滕王阁序》', '《赤壁赋》', '《出师表》'],
    answerIndex: 1,
    difficulty: 2,
  },
  {
    id: 'q_chinese_logic',
    track: 'both',
    subject: '语文',
    text: '填入横线最恰当的一项是: 真正的自律不是压抑欲望,而是____。',
    options: ['让所有欲望消失', '把短期冲动交给长期目标管理', '完全听从他人安排', '永远不犯错误'],
    answerIndex: 1,
    difficulty: 3,
  },
  {
    id: 'q_math_quadratic',
    track: 'both',
    subject: '数学',
    text: '方程 x² - 5x + 6 = 0 的两个根为:',
    options: ['1 和 6', '2 和 3', '-2 和 -3', '0 和 5'],
    answerIndex: 1,
    difficulty: 1,
  },
  {
    id: 'q_math_probability',
    track: 'both',
    subject: '数学',
    text: '掷一枚均匀骰子一次,点数为偶数的概率是:',
    options: ['1/6', '1/3', '1/2', '2/3'],
    answerIndex: 2,
    difficulty: 1,
  },
  {
    id: 'q_math_sequence',
    track: 'both',
    subject: '数学',
    text: '等差数列 {an} 中,a1=3,d=2,则 a10=',
    options: ['19', '21', '23', '25'],
    answerIndex: 1,
    difficulty: 2,
  },
  {
    id: 'q_math_vector',
    track: 'both',
    subject: '数学',
    text: '向量 a=(1,2), b=(3,-1),则 a·b=',
    options: ['1', '3', '5', '-1'],
    answerIndex: 0,
    difficulty: 2,
  },
  {
    id: 'q_math_log',
    track: 'both',
    subject: '数学',
    text: '若 log₂x = 5,则 x =',
    options: ['10', '16', '25', '32'],
    answerIndex: 3,
    difficulty: 2,
  },
  {
    id: 'q_math_derivative',
    track: 'both',
    subject: '数学',
    text: '函数 f(x)=x³-3x 的导数为:',
    options: ['3x²-3', 'x²-3', '3x-3', 'x³-3'],
    answerIndex: 0,
    difficulty: 3,
  },
  {
    id: 'q_math_geometry',
    track: 'both',
    subject: '数学',
    text: '圆 x²+y²=25 的半径是:',
    options: ['5', '10', '25', '√5'],
    answerIndex: 0,
    difficulty: 1,
  },
  {
    id: 'q_english_tense',
    track: 'both',
    subject: '英语',
    text: 'By the time he arrived, the meeting ___.',
    options: ['begins', 'began', 'had begun', 'will begin'],
    answerIndex: 2,
    difficulty: 3,
  },
  {
    id: 'q_english_phrase',
    track: 'both',
    subject: '英语',
    text: 'The phrase "give up" is closest in meaning to:',
    options: ['continue', 'stop trying', 'look after', 'turn on'],
    answerIndex: 1,
    difficulty: 1,
  },
  {
    id: 'q_english_reading',
    track: 'both',
    subject: '英语',
    text: 'In a notice, "Admission is free" means:',
    options: ['You need a ticket', 'You can enter without paying', 'The door is open', 'Seats are limited'],
    answerIndex: 1,
    difficulty: 2,
  },
  {
    id: 'q_english_clause',
    track: 'both',
    subject: '英语',
    text: 'Choose the correct sentence:',
    options: [
      'The book which cover is red is mine.',
      'The book whose cover is red is mine.',
      'The book who cover is red is mine.',
      'The book whom cover is red is mine.',
    ],
    answerIndex: 1,
    difficulty: 4,
  },
  {
    id: 'q_physics_circuit',
    track: '理',
    subject: '理综·物理',
    text: '电阻 R=10Ω,电压 U=5V,通过电阻的电流 I 为:',
    options: ['0.5A', '2A', '5A', '50A'],
    answerIndex: 0,
    difficulty: 2,
  },
  {
    id: 'q_physics_work',
    track: '理',
    subject: '理综·物理',
    text: '力 F=10N 使物体沿力方向移动 3m,做功为:',
    options: ['3J', '10J', '30J', '300J'],
    answerIndex: 2,
    difficulty: 2,
  },
  {
    id: 'q_chem_mole',
    track: '理',
    subject: '理综·化学',
    text: '1 mol 水分子中含有的水分子数约为:',
    options: ['6.02×10²³', '3.14×10²³', '1.00×10²³', '9.8×10²³'],
    answerIndex: 0,
    difficulty: 2,
  },
  {
    id: 'q_chem_ph',
    track: '理',
    subject: '理综·化学',
    text: '常温下,pH=3 的溶液呈:',
    options: ['酸性', '中性', '碱性', '无法判断'],
    answerIndex: 0,
    difficulty: 1,
  },
  {
    id: 'q_bio_dna',
    track: '理',
    subject: '理综·生物',
    text: 'DNA 分子的基本组成单位是:',
    options: ['氨基酸', '核苷酸', '葡萄糖', '脂肪酸'],
    answerIndex: 1,
    difficulty: 2,
  },
  {
    id: 'q_bio_cell',
    track: '理',
    subject: '理综·生物',
    text: '进行光合作用的主要细胞器是:',
    options: ['线粒体', '叶绿体', '核糖体', '高尔基体'],
    answerIndex: 1,
    difficulty: 1,
  },
  {
    id: 'q_physics_energy',
    track: '理',
    subject: '理综·物理',
    text: '质量为 2kg 的物体速度为 3m/s,动能为:',
    options: ['3J', '6J', '9J', '18J'],
    answerIndex: 2,
    difficulty: 3,
  },
  {
    id: 'q_history_reform',
    track: '文',
    subject: '文综·历史',
    text: '戊戌变法发生于哪一年?',
    options: ['1840年', '1895年', '1898年', '1911年'],
    answerIndex: 2,
    difficulty: 2,
  },
  {
    id: 'q_history_movement',
    track: '文',
    subject: '文综·历史',
    text: '五四运动爆发的直接导火索是:',
    options: ['辛亥革命失败', '巴黎和会中国外交失败', '北伐战争开始', '九一八事变'],
    answerIndex: 1,
    difficulty: 3,
  },
  {
    id: 'q_geo_monsoon',
    track: '文',
    subject: '文综·地理',
    text: '我国东部季风区夏季主要盛行:',
    options: ['西北风', '东南风', '东北风', '西南风'],
    answerIndex: 1,
    difficulty: 2,
  },
  {
    id: 'q_geo_river',
    track: '文',
    subject: '文综·地理',
    text: '长江中下游地区容易发生洪涝灾害的主要自然原因是:',
    options: ['降水集中且地势低平', '全年少雨', '海拔极高', '河流短小'],
    answerIndex: 0,
    difficulty: 3,
  },
  {
    id: 'q_politics_market',
    track: '文',
    subject: '文综·政治',
    text: '市场配置资源主要通过哪一机制实现?',
    options: ['价格、供求和竞争', '行政命令', '道德评价', '抽签分配'],
    answerIndex: 0,
    difficulty: 2,
  },
  {
    id: 'q_politics_right',
    track: '文',
    subject: '文综·政治',
    text: '我国公民最基本的政治权利是:',
    options: ['劳动权', '受教育权', '选举权和被选举权', '休息权'],
    answerIndex: 2,
    difficulty: 2,
  },
  {
    id: 'q_history_industrial',
    track: '文',
    subject: '文综·历史',
    text: '第一次工业革命首先开始于:',
    options: ['英国', '法国', '德国', '美国'],
    answerIndex: 0,
    difficulty: 1,
  },
  {
    id: 'q_geo_urbanization',
    track: '文',
    subject: '文综·地理',
    text: '城市化水平通常用什么指标衡量?',
    options: ['农业人口比重', '城市人口占总人口比重', '森林覆盖率', '人均耕地面积'],
    answerIndex: 1,
    difficulty: 2,
  },
];
